version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./instance:/app/instance
    ports:
      - "5050:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://10.136.140.59:6379/0
      - CELERY_RESULT_BACKEND=redis://10.136.140.59:6379/0
    env_file:
      - .env
