version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - ./instance:/app/instance
    ports:
      - "5050:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
