"""added hashed passwords to admins

Revision ID: f32e1479b3e2
Revises: fe59bee6dc59
Create Date: 2024-06-12 21:00:06.828357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32e1479b3e2'
down_revision = 'fe59bee6dc59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
